### ISSUE TITLE
Create separate donation page

### ISSUE THREAD

**Issue by zalaps** [GujaratCovidSupport/gfc-app#5]
Create new donation page at URL gujaratcovidsupport.com/donate
URL to donation page is https://pages.razorpay.com/pl_H3PTWbWsPlMHwz/view

**Comment by pavanmehta91** [comment]
Link to DONATE 👇🏽❤️For INDIAN NATIONALS: http://bit.ly/ahmcovidsupport
For NRIs & FOREIGN NATIONALS: https://milaap.org/fundraisers/support-ahmedabad-covid-support
